site_name: based58
theme:
  name: material
  palette:
    - scheme: default
      primary: lime
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
plugins:
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
            filters:
              - "!^_" # exlude all members starting with _
              - "^__init__$" # but always include __init__ modules and methods
          rendering:
            show_root_heading: true
            show_root_full_path: false
            show_source: false
repo_url: https://github.com/kevinheavey/based58
repo_name: kevinheavey/based58
site_url: https://kevinheavey.github.io/based58/
nav:
  - index.md
  - api_reference.md
extra_css:
  - css/mkdocstrings.css
